### ISSUE TITLE
Not able to convert swagger openapi spec to GraphQL

### ISSUE THREAD

**Issue by candysmurf** [strongloop/oasgraph#64] opened 2018-11-04 21:24 UTC
**Describe the bug**
oasgraph cli was not able to convert openapi spec to GraphQL

**To Reproduce**
```
oasgraph openapi.json
```
**Expected behavior**
GraphQL server is up and running.

**Screenshots**
![screen shot 2018-11-04 at 1 21 13 pm](https://user-images.githubusercontent.com/13841563/47970014-a4a50700-e034-11e8-8f51-26a652ab7266.png)

Please let me know if you need the gist for the openapi.json

**Comment by Alan-Cha** [comment] 2018-11-04 21:57
OASGraph currently does not support external references. I will file an issue for this.

Try copying and pasting the components into your OAS and see if you have any other issues.

**Comment by candysmurf** [comment] 2018-11-04 22:37
@Alan-Cha, thanks for your quick response. How do I copy and paste my components into OAS? a simple example?

**Comment by Alan-Cha** [comment] 2018-11-04 23:03
This could be either pretty easy or a bit involved depending on what your OAS looks like. 

***

You will probably see the following line somewhere in your OAS:

```
"$ref": "http://redfish.dmtf.org/schemas/v1/ServiceRoot.v1_4_0.yaml#/components/schemas/ServiceRoot"
```

To reiterate, the problem is that OASGraph currently does not support external references. 

***

I followed the [link](http://redfish.dmtf.org/schemas/v1/ServiceRoot.v1_4_0.yaml#/components/schemas/ServiceRoot) and discovered that the document is in YAML so the first thing you will need to do is convert it to JSON. 

Next, you should check to see how many external references are present in your OAS.

If this is the only external reference, then all you need to do is replace line above with the `ServiceRoot` schema.

If there are multiple external reference, then you should consider pulling in the [components objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#components-object) and changing all the references to local references. 

To go into more detail, first check if you don't already have a preexisting components object in your OAS. If so, great! You can just copy the full components object into your OAS. If not, you will need to make sure make sure you do not have any collisions. Then you will need to change all your external references to local references, which if they have the same form as above, should look like the following:

```
"$ref": "#/components/schemas/ServiceRoot"
```

**Comment by candysmurf** [comment] 2018-11-05 00:00
@Alan-Cha, thanks for the detailed explanation. I saw a few external links however there is no components object inside OAS yaml file. If I copy all components object, do I need to follow each component link to copy each of them? thanks.

**Comment by Alan-Cha** [comment] 2018-11-05 00:14
If all the links start with `http://redfish.dmtf.org/schemas/v1/ServiceRoot.v1_4_0.yaml`, then that is probably the only components object you need.

If the external references point to different component objects, then you will need to combine them, which could mean you will encounter collisions. 

*** 

In the end, you just need to satisfy the reference. Unfortunately, OASGraph currently does not support external references so you will have to either replace them with whatever they are referencing (for example, copying and pasting a schema object wherever the reference is) or change them into local references (copying and pasting the entire components object at the root level and modifying the reference links).

**Comment by Alan-Cha** [comment] 2018-11-05 00:30
I will close this issue because I have filed issue #65 but please feel free to ask more questions in this thread! 😄

**Closed by Alan-Cha** 2018-11-05 00:30 UTC

**Comment by ErikWittern** [comment] 2018-11-05 14:10
@candysmurf You stated "there is no components object inside OAS yaml file". This could likely be the case because you are using an API specification written in OpenAPI Specification 2.0 (aka "Swagger"), which does not have a `components` object. In that case, there should be a `definitions` object, though, which contains descriptions of the data being sent to or returned from the API. Maybe within the referenced "ServiceRoot.v1_4_0.yaml" there is also a `definitions` object from which you could copy the `ServiceRoot` schema definition?!

**Comment by candysmurf** [comment] 2019-01-16 23:09
I would like to follow up on this. We decided to use OASGraph and would like to see if you support yaml file and external references yet? @Alan-Cha & @ErikWittern

**Comment by Alan-Cha** [comment] 2019-01-17 03:55
@candysmurf We added YAML support to the CLI tool (although we have yet to release a new version). We do not plan on adding external reference resolution right now, however. There are a few reasons. First of all, although this would be a nice feature to have, we wonder if it lies outside the scope of OASGraph. This should be a library of its own. Secondly, development of OASGraph has slowed down. Erik and I are the main contributors to OASGraph and we are busy working on other projects right now. This does not mean we will stop development on OASGraph. We definitely plan on coming back to it soon but as of now, we can only tackle small updates to this project.

**Comment by candysmurf** [comment] 2019-01-18 18:22
Thanks, Alan for the update. I find a way to do it on the CLI. It's a nice
to have feature but not must.
